### ISSUE TITLE
Code generation of all onvif helper methods.

### ISSUE THREAD

**Issue by itsparth** [faithoflifedev/easy_onvif_workspace#62]
Hello I wanted to understand how the current list of helper methods were created, manually or is there some automation used?
I would like to add some more methods to the library so need guidance on what is the right way.

I found this https://github.com/ozdoganoguzhan/dart-xsd-wsdl-gen
Although it works for most cases, still many of the features are not supported.

**Comment by faithoflifedev** [comment]
Hi @itsparth,

The helper methods and the rest of the package have all been created manually, please feel free to submit a PR with any changes.
